# -*- coding: utf-8 -*-
"""modelV3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgUSWGPyPrxOfx0PetH6BC44Acrzno4b
"""

"""
Activity Recognition using LSTM - UCI HAR Dataset
Uses both Accelerometer + Gyroscope data (6 channels)
Clean, simple code for model training
"""

# ============================================================================
# IMPORTS
# ============================================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully!")
print(f"TensorFlow version: {tf.__version__}")
print(f"GPU available: {len(tf.config.list_physical_devices('GPU')) > 0}")

# ============================================================================
# DOWNLOAD AND EXTRACT UCI HAR DATASET
# ============================================================================

print("\n" + "="*70)
print("STEP 1: DOWNLOAD UCI HAR DATASET")
print("="*70)

# Download dataset
print("\nDownloading UCI HAR dataset...")
!wget -q https://archive.ics.uci.edu/ml/machine-learning-databases/00240/UCI%20HAR%20Dataset.zip
!unzip -q "UCI HAR Dataset.zip"

print("✓ Dataset downloaded and extracted!")

# ============================================================================
# LOAD DATASET
# ============================================================================

print("\n" + "="*70)
print("STEP 2: LOAD UCI HAR DATASET")
print("="*70)

def load_uci_har_data():
    """
    Load UCI HAR dataset from Inertial Signals folder
    Returns data with shape (samples, 128, 6) for 6 sensor channels
    """

    # Activity labels
    activity_labels = {
        1: 'Walking',
        2: 'Walking_Upstairs',
        3: 'Walking_Downstairs',
        4: 'Sitting',
        5: 'Standing',
        6: 'Laying'
    }

    print("Loading training data...")

    # Load training data (Inertial Signals)
    train_path = 'UCI HAR Dataset/train/Inertial Signals/'

    # Accelerometer data
    train_acc_x = np.loadtxt(train_path + 'body_acc_x_train.txt')
    train_acc_y = np.loadtxt(train_path + 'body_acc_y_train.txt')
    train_acc_z = np.loadtxt(train_path + 'body_acc_z_train.txt')

    # Gyroscope data
    train_gyro_x = np.loadtxt(train_path + 'body_gyro_x_train.txt')
    train_gyro_y = np.loadtxt(train_path + 'body_gyro_y_train.txt')
    train_gyro_z = np.loadtxt(train_path + 'body_gyro_z_train.txt')

    # Stack along last axis to get shape (samples, 128, 6)
    X_train = np.stack([train_acc_x, train_acc_y, train_acc_z,
                        train_gyro_x, train_gyro_y, train_gyro_z], axis=2)

    # Load training labels
    y_train = np.loadtxt('UCI HAR Dataset/train/y_train.txt')
    y_train = y_train - 1  # Convert to 0-based indexing

    print("Loading test data...")

    # Load test data (Inertial Signals)
    test_path = 'UCI HAR Dataset/test/Inertial Signals/'

    # Accelerometer data
    test_acc_x = np.loadtxt(test_path + 'body_acc_x_test.txt')
    test_acc_y = np.loadtxt(test_path + 'body_acc_y_test.txt')
    test_acc_z = np.loadtxt(test_path + 'body_acc_z_test.txt')

    # Gyroscope data
    test_gyro_x = np.loadtxt(test_path + 'body_gyro_x_test.txt')
    test_gyro_y = np.loadtxt(test_path + 'body_gyro_y_test.txt')
    test_gyro_z = np.loadtxt(test_path + 'body_gyro_z_test.txt')

    # Stack along last axis
    X_test = np.stack([test_acc_x, test_acc_y, test_acc_z,
                       test_gyro_x, test_gyro_y, test_gyro_z], axis=2)

    # Load test labels
    y_test = np.loadtxt('UCI HAR Dataset/test/y_test.txt')
    y_test = y_test - 1  # Convert to 0-based indexing

    print(f"\n✓ Dataset loaded successfully!")
    print(f"\nTraining data:")
    print(f"  X_train shape: {X_train.shape} (samples, timesteps, channels)")
    print(f"  y_train shape: {y_train.shape}")
    print(f"\nTest data:")
    print(f"  X_test shape: {X_test.shape}")
    print(f"  y_test shape: {y_test.shape}")

    # Show activity distribution
    print(f"\n📊 Activity Distribution:")
    print(f"{'='*50}")
    for i, activity in activity_labels.items():
        train_count = np.sum(y_train == i-1)
        test_count = np.sum(y_test == i-1)
        print(f"  {activity:20s}: Train={train_count:4d}, Test={test_count:4d}")

    return X_train, y_train.astype(int), X_test, y_test.astype(int), activity_labels

# Load data
X_train, y_train, X_test, y_test, activity_labels = load_uci_har_data()

# ============================================================================
# VISUALIZE DATA
# ============================================================================

print("\n" + "="*70)
print("STEP 3: DATA VISUALIZATION")
print("="*70)

# Plot activity distribution
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Training distribution
train_counts = [np.sum(y_train == i) for i in range(6)]
axes[0].bar(activity_labels.values(), train_counts, color='skyblue', edgecolor='black')
axes[0].set_title('Training Data Distribution', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Activity')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=45)

# Test distribution
test_counts = [np.sum(y_test == i) for i in range(6)]
axes[1].bar(activity_labels.values(), test_counts, color='lightcoral', edgecolor='black')
axes[1].set_title('Test Data Distribution', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Activity')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# Plot sample sensor data
sample_idx = 0
sample_activity = activity_labels[y_train[sample_idx] + 1]

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
sensor_names = ['Acc_X', 'Acc_Y', 'Acc_Z', 'Gyro_X', 'Gyro_Y', 'Gyro_Z']

for i, (ax, name) in enumerate(zip(axes.flat, sensor_names)):
    ax.plot(X_train[sample_idx, :, i], linewidth=2)
    ax.set_title(f'{name} - {sample_activity}', fontweight='bold')
    ax.set_xlabel('Sample')
    ax.set_ylabel('Value')
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.show()

print("✓ Data visualization complete!")

# ============================================================================
# BUILD LSTM MODEL
# ============================================================================

print("\n" + "="*70)
print("STEP 4: BUILD LSTM MODEL")
print("="*70)

num_classes = 6
input_shape = (X_train.shape[1], X_train.shape[2])  # (128, 6)

model = keras.Sequential([
    # First LSTM layer
    layers.LSTM(128, return_sequences=True, input_shape=input_shape),
    layers.Dropout(0.3),

    # Second LSTM layer
    layers.LSTM(64),
    layers.Dropout(0.3),

    # Dense layers
    layers.Dense(32, activation='relu'),
    layers.Dropout(0.2),

    # Output layer
    layers.Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("✓ Model built successfully!")
print(f"\nModel Architecture:")
model.summary()

# ============================================================================
# TRAIN MODEL
# ============================================================================

print("\n" + "="*70)
print("STEP 5: TRAIN MODEL")
print("="*70)

EPOCHS = 50  # Increase epochs
BATCH_SIZE = 32  # Smaller batch for better learning

# Add class weights to handle imbalance
from sklearn.utils import class_weight
class_weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train),
    y=y_train
)
class_weight_dict = dict(enumerate(class_weights))

print(f"\nTraining configuration:")
print(f"  Epochs: {EPOCHS}")
print(f"  Batch size: {BATCH_SIZE}")
print(f"  Training samples: {len(X_train):,}")
print(f"  Validation samples: {len(X_test):,}")
print(f"  Class weights: {class_weight_dict}")

print(f"\n🚀 Starting training...\n")

history = model.fit(
    X_train, y_train,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    validation_data=(X_test, y_test),
    class_weight=class_weight_dict,  # ADD THIS!
    verbose=1
)

print("\n✓ Training completed!")

# ============================================================================
# EVALUATE MODEL
# ============================================================================

print("\n" + "="*70)
print("STEP 6: EVALUATE MODEL")
print("="*70)

# Evaluate on test set
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"\n{'='*50}")
print(f"TEST SET RESULTS:")
print(f"{'='*50}")
print(f"  Loss: {test_loss:.4f}")
print(f"  Accuracy: {test_accuracy*100:.2f}%")
print(f"{'='*50}")

# Make predictions
y_pred = model.predict(X_test, verbose=0)
y_pred_classes = np.argmax(y_pred, axis=1)

# Classification report
print(f"\n📋 Detailed Classification Report:")
print(f"{'='*70}")
print(classification_report(y_test, y_pred_classes,
                          target_names=activity_labels.values(),
                          digits=3))

# Per-class accuracy
print(f"\n📊 Per-Class Accuracy:")
print(f"{'='*50}")
for i, activity in activity_labels.items():
    mask = y_test == (i-1)
    if mask.sum() > 0:
        class_acc = accuracy_score(y_test[mask], y_pred_classes[mask])
        print(f"  {activity:20s}: {class_acc*100:5.2f}%")

# ============================================================================
# VISUALIZATIONS
# ============================================================================

print("\n" + "="*70)
print("STEP 7: VISUALIZATIONS")
print("="*70)

fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# Accuracy plot
axes[0, 0].plot(history.history['accuracy'], label='Training', linewidth=2.5)
axes[0, 0].plot(history.history['val_accuracy'], label='Validation', linewidth=2.5)
axes[0, 0].set_title('Model Accuracy', fontsize=12, fontweight='bold')
axes[0, 0].set_xlabel('Epoch')
axes[0, 0].set_ylabel('Accuracy')
axes[0, 0].legend()
axes[0, 0].grid(alpha=0.3)

# Loss plot
axes[0, 1].plot(history.history['loss'], label='Training', linewidth=2.5)
axes[0, 1].plot(history.history['val_loss'], label='Validation', linewidth=2.5)
axes[0, 1].set_title('Model Loss', fontsize=12, fontweight='bold')
axes[0, 1].set_xlabel('Epoch')
axes[0, 1].set_ylabel('Loss')
axes[0, 1].legend()
axes[0, 1].grid(alpha=0.3)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_classes)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=activity_labels.values(),
            yticklabels=activity_labels.values(),
            ax=axes[1, 0])
axes[1, 0].set_title('Confusion Matrix', fontsize=12, fontweight='bold')
axes[1, 0].set_ylabel('True Label')
axes[1, 0].set_xlabel('Predicted Label')
plt.setp(axes[1, 0].get_xticklabels(), rotation=45, ha='right')

# Normalized confusion matrix
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] * 100
sns.heatmap(cm_norm, annot=True, fmt='.1f', cmap='Greens',
            xticklabels=activity_labels.values(),
            yticklabels=activity_labels.values(),
            ax=axes[1, 1])
axes[1, 1].set_title('Normalized Confusion Matrix (%)', fontsize=12, fontweight='bold')
axes[1, 1].set_ylabel('True Label')
axes[1, 1].set_xlabel('Predicted Label')
plt.setp(axes[1, 1].get_xticklabels(), rotation=45, ha='right')

plt.tight_layout()
plt.show()

print("✓ Visualizations complete!")

# ============================================================================
# DEMO PREDICTIONS
# ============================================================================

print("\n" + "="*70)
print("STEP 8: DEMO PREDICTIONS")
print("="*70)

# Test with random samples
for i in range(5):
    idx = np.random.randint(0, len(X_test))
    sample = X_test[idx].reshape(1, 128, 6)

    prediction = model.predict(sample, verbose=0)[0]
    predicted_class = np.argmax(prediction)

    true_activity = activity_labels[y_test[idx] + 1]
    pred_activity = activity_labels[predicted_class + 1]

    print(f"\nSample {i+1}:")
    print(f"  True: {true_activity}")
    print(f"  Predicted: {pred_activity}")
    print(f"  Confidence: {prediction[predicted_class]*100:.1f}%")

    if predicted_class == y_test[idx]:
        print(f"  ✓ CORRECT")
    else:
        print(f"  ✗ INCORRECT")

# ============================================================================
# ESP32 INTEGRATION GUIDE
# ============================================================================

print("\n" + "="*70)
print("ESP32 INTEGRATION GUIDE")
print("="*70)


# ============================================================================
# SUMMARY
# ============================================================================

print("\n" + "="*70)
print("TRAINING COMPLETE!")
print("="*70)

summary = f"""
✅ MODEL TRAINED SUCCESSFULLY!

📊 FINAL RESULTS:
{'='*50}
  Test Accuracy: {test_accuracy*100:.2f}%
  Test Loss: {test_loss:.4f}

📋 DATASET INFO:
{'='*50}
  Training samples: {len(X_train):,}
  Test samples: {len(X_test):,}
  Input shape: (128, 6) - 128 timesteps, 6 sensor channels
  Activities: 6 (Walking, Upstairs, Downstairs, Sitting, Standing, Laying)

"""

print(summary)

print("\n" + "="*70)