# -*- coding: utf-8 -*-
"""modelV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aobEToy-Fw6qi3CRztCdOWX96OA1xTFc
"""

"""
Activity Recognition using LSTM - WISDM Dataset (Safe Version)
→ Includes: dataset upload, parsing with error handling,
   window creation, grouped user split (no leakage), normalization,
   model training with EarlyStopping, evaluation, and visualization.
"""

# =====================================================================
# IMPORTS
# =====================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers
import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully!")
print(f"TensorFlow version: {tf.__version__}")
print(f"GPU available: {len(tf.config.list_physical_devices('GPU')) > 0}")

# =====================================================================
# STEP 1: UPLOAD + LOAD WISDM DATASET
# =====================================================================
from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]  # e.g., "WISDM_ar_v1.1_raw.txt"

def load_wisdm_data(filename):
    """Load WISDM raw text data safely, skip malformed lines."""
    print("Loading dataset...")
    data_list = []
    skipped = 0

    with open(filename, 'r') as f:
        for line in f:
            line = line.strip().replace(';', '')
            if not line:
                continue
            parts = line.split(',')
            try:
                if len(parts) >= 6:
                    user = int(parts[0])
                    activity = parts[1].strip()
                    timestamp = int(parts[2])
                    x, y, z = map(float, parts[3:6])
                    data_list.append([user, activity, timestamp, x, y, z])
                else:
                    skipped += 1
            except:
                skipped += 1
                continue

    df = pd.DataFrame(data_list, columns=['user', 'activity', 'timestamp', 'x', 'y', 'z'])
    print(f"✓ Loaded {len(df):,} samples ({skipped:,} skipped rows).")
    print("Users:", df['user'].nunique(), "| Activities:", df['activity'].nunique())
    print("\nActivity counts:")
    print(df['activity'].value_counts())
    return df

wisdm_data = load_wisdm_data(filename)

# =====================================================================
# STEP 2: CREATE SEGMENTS (with user tracking)
# =====================================================================
def create_segments_with_user(data, window_size=80, step=40):
    segments, labels, users = [], [], []
    for user in data['user'].unique():
        user_data = data[data['user'] == user]
        for activity in user_data['activity'].unique():
            act_data = user_data[user_data['activity'] == activity]
            values = act_data[['x','y','z']].values
            for i in range(0, len(values) - window_size, step):
                segments.append(values[i:i+window_size])
                labels.append(activity)
                users.append(user)
    return np.array(segments), np.array(labels), np.array(users)

X, y, users = create_segments_with_user(wisdm_data)
print(f"Created {len(X):,} segments | Shape: {X.shape}")

# Encode labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
num_classes = len(label_encoder.classes_)
print("Encoded classes:", list(label_encoder.classes_))

# =====================================================================
# STEP 3: GROUPED TRAIN/TEST SPLIT (avoid leakage)
# =====================================================================
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y_encoded, groups=users))

X_train_all, X_test = X[train_idx], X[test_idx]
y_train_all, y_test = y_encoded[train_idx], y_encoded[test_idx]
users_train_all, users_test = users[train_idx], users[test_idx]

print("Unique train users:", np.unique(users_train_all))
print("Unique test users :", np.unique(users_test))

# Split train -> train/val by users
gss2 = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=24)
train_idx2, val_idx = next(gss2.split(X_train_all, y_train_all, groups=users_train_all))

X_train, X_val = X_train_all[train_idx2], X_train_all[val_idx]
y_train, y_val = y_train_all[train_idx2], y_train_all[val_idx]
users_train, users_val = users_train_all[train_idx2], users_train_all[val_idx]

print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")

# =====================================================================
# STEP 4: NORMALIZATION
# =====================================================================
mean = X_train.mean(axis=(0,1))
std  = X_train.std(axis=(0,1)) + 1e-8
X_train = (X_train - mean) / std
X_val   = (X_val - mean) / std
X_test  = (X_test - mean) / std

# =====================================================================
# STEP 5: BUILD MODEL
# =====================================================================
input_shape = (X_train.shape[1], X_train.shape[2])

def build_model(input_shape=input_shape, num_classes=num_classes):
    model = keras.Sequential([
        layers.LSTM(64, return_sequences=True, input_shape=input_shape,
                    kernel_regularizer=regularizers.l2(1e-4), recurrent_dropout=0.15),
        layers.Dropout(0.4),
        layers.LSTM(32, kernel_regularizer=regularizers.l2(1e-4), recurrent_dropout=0.15),
        layers.Dropout(0.4),
        layers.Dense(32, activation='relu', kernel_regularizer=regularizers.l2(1e-4)),
        layers.Dropout(0.3),
        layers.Dense(num_classes, activation='softmax')
    ])
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=1e-3),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

model = build_model()
model.summary()

# =====================================================================
# STEP 6: TRAIN MODEL
# =====================================================================
es = keras.callbacks.EarlyStopping(monitor='val_loss', patience=6, restore_best_weights=True, verbose=1)
rlr = keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6, verbose=1)

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=50,
    batch_size=64,
    callbacks=[es, rlr],
    verbose=1
)

# =====================================================================
# STEP 7: EVALUATION (on held-out users)
# =====================================================================
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\nFinal Grouped Test Accuracy: {test_acc*100:.2f}%  |  Test Loss: {test_loss:.4f}")

y_pred = np.argmax(model.predict(X_test, verbose=0), axis=1)
print("\nClassification Report (grouped test):")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_, digits=4))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)
plt.title('Confusion Matrix (Grouped Test)')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# =====================================================================
# STEP 8: LEARNING CURVES
# =====================================================================
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.title('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.title('Loss')
plt.legend()
plt.tight_layout()
plt.show()