version = 0.1

[default.deploy.parameters]
stack_name = "health-monitor-backend"
resolve_s3 = true
s3_prefix = "health-monitor-backend"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "DeployColdStorage=\"false\""

[default.global.parameters]
region = "ap-south-1"
